import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

// AES-256-GCM encryption of the assembled prompt
async function encryptPrompt(plaintext, keyStr) {
  const enc = new TextEncoder();
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    enc.encode(keyStr.padEnd(32, '0').slice(0, 32)),
    { name: 'AES-GCM' },
    false,
    ['encrypt']
  );
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    keyMaterial,
    enc.encode(plaintext)
  );
  // Store as base64(iv):base64(ciphertext)
  const toB64 = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf)));
  return `${toB64(iv)}:${toB64(ciphertext)}`;
}

function buildPrompt(analysis, prompts) {
  const get = (section) => {
    const p = prompts.find(p => p.prompt_section === section);
    return p ? p.prompt_text : '';
  };

  const intake = analysis.intake_data || {};
  const followup = analysis.followup_answers || {};

  // Replace common tokens
  const replace = (text) => text
    .replace(/\[ASSESSMENT_TYPE\]/g, analysis.assessment_type || '')
    .replace(/\[PROPERTY_TYPE\]/g, analysis.property_type || '')
    .replace(/\[LOCATION_CLASS\]/g, analysis.location_class || '')
    .replace(/\[OUTPUT_FORMAT\]/g, analysis.output_format || 'narrative')
    .replace(/\[ADDRESS\]/g, intake.address || '')
    .replace(/\[CLIENT_RELATIONSHIP\]/g, intake.client_relationship || '')
    .replace(/\[INTAKE_JSON\]/g, JSON.stringify(intake, null, 2))
    .replace(/\[FOLLOWUP_JSON\]/g, JSON.stringify(followup, null, 2));

  const formatModifier = {
    narrative: 'Write in flowing, professional prose paragraphs. Use headers to organize sections.',
    structured: 'Use a structured format with clear labeled sections, sub-sections, and data tables where applicable.',
    bullets: 'Use concise bullet points and numbered lists throughout. Minimize prose.',
  }[analysis.output_format] || '';

  const sections = [
    replace(get('system_instructions')),
    replace(get('intake_template')),
    replace(get('valuation_module')),
    replace(get('migration_module')),
    replace(get('archetype_module')),
    replace(get('avm_module')),
    replace(get('listing_strategy_module')),
    `\n\n## Output Format Instructions\n${formatModifier}`,
    replace(get('disclaimer_footer')),
  ].filter(Boolean).join('\n\n---\n\n');

  return sections;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { analysisId } = await req.json();
    if (!analysisId) return Response.json({ error: 'analysisId required' }, { status: 400 });

    // Load analysis
    const analyses = await base44.asServiceRole.entities.Analysis.filter({ id: analysisId });
    const analysis = analyses[0];
    if (!analysis) return Response.json({ error: 'Analysis not found' }, { status: 404 });

    // Authorization: only the owner or an admin can assemble
    if (analysis.run_by_email !== user.email && user.role !== 'platform_owner' && user.role !== 'brokerage_admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    // Load matching prompts from prompt_library
    const prompts = await base44.asServiceRole.entities.PromptLibrary.filter({
      assessment_type: analysis.assessment_type,
      is_active: true,
    });

    // Also load generic/all property_type prompts
    const genericPrompts = await base44.asServiceRole.entities.PromptLibrary.filter({
      property_type: 'all',
      is_active: true,
    });

    const allPrompts = [...prompts, ...genericPrompts];

    // If no prompts in library yet, build a sensible default prompt
    let assembled;
    if (allPrompts.length === 0) {
      const intake = analysis.intake_data || {};
      const followup = analysis.followup_answers || {};
      assembled = `You are PropPrompt™ v3.0 — an AI-calibrated real estate analysis engine for Eastern Massachusetts developed by Sherwood & Company.

## Analysis Request
- Assessment Type: ${analysis.assessment_type}
- Property Type: ${analysis.property_type}
- Location Class: ${analysis.location_class || 'Not specified'}
- Output Format: ${analysis.output_format || 'narrative'}
- Client Relationship: ${intake.client_relationship || 'Not specified'}

## Property Details
${JSON.stringify(intake, null, 2)}

## Follow-Up Context
${Object.keys(followup).length > 0 ? JSON.stringify(followup, null, 2) : 'No follow-up answers provided.'}

## Instructions
Provide a comprehensive, professional real estate analysis based on the above data. Apply Eastern Massachusetts market expertise, current market conditions, and relevant comparable analysis frameworks.

---
**DISCLAIMER:** This analysis is generated by artificial intelligence and is intended solely as a professional research aid for licensed real estate practitioners. It does not constitute an appraisal, a Broker Price Opinion (BPO), or legal advice. All figures, valuations, and recommendations must be independently verified by the agent/broker of record before use in any client-facing communication. Sherwood & Company and its affiliates assume no liability for decisions made based on AI-generated content. © 2026 Sherwood & Company. PropPrompt™ is a proprietary system.`;
    } else {
      assembled = buildPrompt(analysis, allPrompts);
    }

    // Encrypt the prompt before storing
    const encKey = Deno.env.get('ENCRYPTION_KEY') || '';
    const encryptedPrompt = await encryptPrompt(assembled, encKey);

    // Store encrypted prompt and update status
    await base44.asServiceRole.entities.Analysis.update(analysisId, {
      prompt_assembled: encryptedPrompt,
      status: 'in_progress',
    });

    // Return a confirmation token (not the prompt itself)
    return Response.json({
      success: true,
      analysisId,
      status: 'in_progress',
      promptSections: allPrompts.length,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});