import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

/**
 * Push a formatted key-findings summary to the user's connected CRM.
 * Logs every attempt to CrmPushLog regardless of outcome.
 */
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { analysisId, crmConnectionId, crmContactId } = await req.json();
    if (!analysisId || !crmConnectionId) {
      return Response.json({ error: 'analysisId and crmConnectionId required' }, { status: 400 });
    }

    // Fetch analysis
    const analyses = await base44.entities.Analysis.filter({ id: analysisId });
    const analysis = analyses[0];
    if (!analysis) return Response.json({ error: 'Analysis not found' }, { status: 404 });

    // Fetch CRM connection
    const connections = await base44.entities.CrmConnection.filter({ id: crmConnectionId, user_email: user.email });
    const conn = connections[0];
    if (!conn) return Response.json({ error: 'CRM connection not found' }, { status: 404 });

    // Build formatted summary (key findings only — NOT full output_text)
    const address = analysis.intake_data?.address || 'Property';
    const summary = buildSummary(analysis);

    let result = { success: false, crm_record_id: null, error_message: null, http_status_code: null };

    if (conn.crm_provider === 'follow_up_boss') {
      result = await pushFollowUpBoss(conn, address, summary, crmContactId);
    } else if (conn.crm_provider === 'kvcore') {
      result = await pushKvCore(conn, address, summary, crmContactId);
    } else if (conn.crm_provider === 'salesforce') {
      result = await pushSalesforce(conn, address, summary, crmContactId);
    } else if (conn.crm_provider === 'lofty') {
      result = await pushLofty(conn, address, summary, crmContactId);
    } else {
      return Response.json({ error: 'Unsupported CRM provider' }, { status: 400 });
    }

    // Log the attempt
    await base44.entities.CrmPushLog.create({
      analysis_id: analysisId,
      crm_connection_id: crmConnectionId,
      user_email: user.email,
      crm_provider: conn.crm_provider,
      push_type: conn.default_push_format || 'note',
      crm_contact_id: crmContactId || null,
      crm_record_id: result.crm_record_id || null,
      status: result.success ? 'success' : 'failed',
      error_message: result.error_message || null,
      http_status_code: result.http_status_code || null,
      pushed_at: new Date().toISOString(),
    });

    // Update analysis crm_push_status
    if (result.success) {
      await base44.entities.Analysis.update(analysisId, { crm_push_status: 'pushed' });
    } else {
      await base44.entities.Analysis.update(analysisId, { crm_push_status: 'failed' });
    }

    return Response.json({ success: result.success, error: result.error_message });

  } catch (err) {
    console.error('crmPush error:', err);
    return Response.json({ error: err.message }, { status: 500 });
  }
});

function buildSummary(analysis) {
  const type = analysis.assessment_type?.replace(/_/g, ' ') || 'Analysis';
  const propType = analysis.property_type?.replace(/_/g, ' ') || '';
  const date = new Date(analysis.created_date).toLocaleDateString();

  // Extract first ~600 chars of output as key findings (safe summary, not full output)
  const rawOutput = analysis.output_text || '';
  const excerpt = rawOutput.length > 600
    ? rawOutput.substring(0, 600).replace(/[#*`]/g, '').trim() + '...'
    : rawOutput.replace(/[#*`]/g, '').trim();

  return `PropPrompt™ ${type} — ${propType}
Date: ${date}
Address: ${analysis.intake_data?.address || 'N/A'}
AI Platform: ${analysis.ai_platform || 'N/A'}

KEY FINDINGS SUMMARY:
${excerpt || 'Analysis complete. See attached PDF for full report.'}

--- Generated by PropPrompt™ | Sherwood & Company, Brokered by Compass ---`;
}

async function pushFollowUpBoss(conn, address, summary, contactId) {
  const apiKey = conn.encrypted_api_key; // stored as plaintext API key (FUB uses Basic auth)
  const authHeader = 'Basic ' + btoa(apiKey + ':');
  const body = {
    type: 'Note',
    description: summary,
    ...(contactId ? { personId: contactId } : {}),
  };
  try {
    const res = await fetch('https://api.followupboss.com/v1/events', {
      method: 'POST',
      headers: { 'Authorization': authHeader, 'Content-Type': 'application/json', 'X-System': 'PropPrompt', 'X-System-Key': 'propprompt' },
      body: JSON.stringify(body),
    });
    const data = await res.json().catch(() => ({}));
    return { success: res.ok, crm_record_id: data.id?.toString() || null, http_status_code: res.status, error_message: res.ok ? null : (data.errorMessage || `HTTP ${res.status}`) };
  } catch (e) {
    return { success: false, error_message: e.message };
  }
}

async function pushKvCore(conn, address, summary, contactId) {
  const instanceUrl = conn.crm_account_name || ''; // stored instance URL
  const token = conn.encrypted_api_key;
  const endpoint = `${instanceUrl}/api/v1/notes`;
  try {
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ subject: `PropPrompt™ Analysis — ${address}`, body: summary, contact_id: contactId || null }),
    });
    const data = await res.json().catch(() => ({}));
    return { success: res.ok, crm_record_id: data.id?.toString() || null, http_status_code: res.status, error_message: res.ok ? null : `HTTP ${res.status}` };
  } catch (e) {
    return { success: false, error_message: e.message };
  }
}

async function pushSalesforce(conn, address, summary, contactId) {
  const instanceUrl = conn.crm_account_name || '';
  const accessToken = conn.oauth_access_token;
  try {
    // Create Task
    const taskRes = await fetch(`${instanceUrl}/services/data/v58.0/sobjects/Task`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        Subject: `PropPrompt™ Analysis — ${address}`,
        Description: summary,
        Status: 'Completed',
        Priority: 'Normal',
        ...(contactId ? { WhoId: contactId } : {}),
      }),
    });
    const taskData = await taskRes.json().catch(() => ({}));
    return { success: taskRes.ok, crm_record_id: taskData.id || null, http_status_code: taskRes.status, error_message: taskRes.ok ? null : JSON.stringify(taskData) };
  } catch (e) {
    return { success: false, error_message: e.message };
  }
}

async function pushLofty(conn, address, summary, contactId) {
  const apiKey = conn.encrypted_api_key;
  if (!contactId) return { success: false, error_message: 'Lofty requires a contact ID' };
  try {
    const res = await fetch(`https://api.lofty.com/api/v1/contacts/${contactId}/notes`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: summary }),
    });
    const data = await res.json().catch(() => ({}));
    return { success: res.ok, crm_record_id: data.id?.toString() || null, http_status_code: res.status, error_message: res.ok ? null : `HTTP ${res.status}` };
  } catch (e) {
    return { success: false, error_message: e.message };
  }
}