/**
 * generateFairHousingReviews — Monthly scheduled job.
 * Creates a FairHousingReview record for each brokerage_admin / team_lead
 * who is the top of their org hierarchy. Generates review text via Claude
 * using the Addendum A4.3 prompt template.
 *
 * Called by: scheduled automation (1st of each month)
 * Also callable by platform_owner via direct invoke for testing.
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const FAIR_HOUSING_PROMPT = (org, reviewer, month) => `You are PropPrompt™ Fair Housing Compliance AI.

Generate a MONTHLY FAIR HOUSING COMPLIANCE REVIEW for:
- Organization: ${org.name} (${org.org_type})
- Reviewer: ${reviewer}
- Review Period: ${month}
- Licensed States: ${(org.licensed_markets || ['MA']).join(', ')}

Your review MUST include all of the following sections, formatted as a numbered compliance checklist:

1. EQUAL OPPORTUNITY STATEMENT
   - Affirm commitment to fair housing under Title VIII of the Civil Rights Act of 1968
   - Include state-specific additions for: ${(org.licensed_markets || ['MA']).join(', ')}

2. PROTECTED CLASS REVIEW
   Checklist for each: Race, Color, Religion, National Origin, Sex, Disability, Familial Status
   Plus MA state additions: Age, Sexual Orientation, Marital Status, Military/Veteran Status, Source of Income
   For each class: ☐ No discriminatory language used in marketing ☐ No steering based on this class ☐ AI outputs reviewed for bias

3. AI-GENERATED CONTENT COMPLIANCE (PropPrompt™ Specific)
   ☐ Reviewed AI outputs for demographic steering indicators
   ☐ Confirmed no neighborhood characterizations based on protected classes
   ☐ Confirmed no predictive language about school quality tied to demographics
   ☐ Confirmed no redlining-adjacent language in location assessments

4. MARKETING & ADVERTISING REVIEW
   ☐ All listings include Equal Housing Opportunity logo/statement
   ☐ No exclusionary language in property descriptions
   ☐ Social media ads comply with fair housing targeting rules

5. TRANSACTION REVIEW
   ☐ Comparable properties shown to all buyers regardless of protected class
   ☐ No differential service levels documented
   ☐ Offer handling documented for any competitive situations

6. TRAINING ATTESTATION
   ☐ All agents completed annual fair housing training
   ☐ New agents received onboarding fair housing module

7. INCIDENT LOG
   No incidents to report this period (if incidents occurred, document separately per Addendum A4.6)

8. REVIEWER CERTIFICATION
   By signing below, I certify that I have reviewed all AI-generated analyses produced by my organization during ${month}, that I have found no fair housing violations, and that the above checklist accurately reflects our compliance status for this period.

---
IMPORTANT: This review was auto-generated by PropPrompt™ AI. The reviewer must read it in full, make any necessary manual corrections, and sign it electronically. This document does not constitute legal advice. Consult your broker's legal counsel for any fair housing concerns.`;

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Accept both scheduled (no auth) and manual invocation (platform_owner)
    let isPlatformOwner = false;
    try {
      const user = await base44.auth.me();
      if (user?.role === 'platform_owner') isPlatformOwner = true;
    } catch (_) {}

    const now = new Date();
    const month = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

    // Get all active orgs
    const orgs = await base44.asServiceRole.entities.Organization.list();
    const activeOrgs = orgs.filter((o) => o.fair_housing_compliance_enabled && o.status === 'active');

    const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
    if (!apiKey) {
      console.error('[generateFairHousingReviews] No ANTHROPIC_API_KEY');
      return Response.json({ error: 'No Claude API key configured' }, { status: 500 });
    }

    let created = 0;
    let skipped = 0;

    for (const org of activeOrgs) {
      // Check if review already exists for this month
      const existing = await base44.asServiceRole.entities.FairHousingReview.filter({
        org_id: org.id,
        review_period_month: month,
      });
      if (existing.length > 0) { skipped++; continue; }

      // Find the top reviewer (brokerage_admin or owner)
      const reviewer = org.owner_email;
      if (!reviewer) { skipped++; continue; }

      // Generate review via Claude
      const prompt = FAIR_HOUSING_PROMPT(org, reviewer, month);
      let reviewText = '';
      try {
        const res = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'x-api-key': apiKey,
            'anthropic-version': '2023-06-01',
            'content-type': 'application/json',
          },
          body: JSON.stringify({
            model: 'claude-opus-4-5',
            max_tokens: 2048,
            messages: [{ role: 'user', content: prompt }],
          }),
        });
        const data = await res.json();
        reviewText = data.content?.[0]?.text || prompt;
      } catch (e) {
        console.error(`[generateFairHousingReviews] Claude error for org ${org.id}:`, e);
        reviewText = prompt; // fallback to template
      }

      await base44.asServiceRole.entities.FairHousingReview.create({
        org_id: org.id,
        reviewer_email: reviewer,
        review_period_month: month,
        licensed_states: org.licensed_markets || ['MA'],
        review_text: reviewText,
        review_generation_model: 'claude-opus-4-5',
        status: 'pending',
      });

      created++;
      console.log(`[generateFairHousingReviews] Created review for org=${org.id} month=${month}`);
    }

    return Response.json({ created, skipped, month });
  } catch (error) {
    console.error('[generateFairHousingReviews] error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});