/**
 * generateFairHousingReviews — Monthly scheduled job.
 * For every active org with fair_housing_compliance_enabled, find the highest-hierarchy
 * user (brokerage_admin or team_lead), generate a Claude review, and store it.
 * Called by: scheduled automation (1st of each month).
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const REVIEW_PROMPT = (orgName, states, period) => `You are a fair housing compliance AI assistant for a real estate brokerage.

Generate a monthly Fair Housing Compliance Review for:
- Organization: ${orgName}
- Licensed States: ${states.join(", ") || "Massachusetts"}
- Review Period: ${period}

Your review must cover:

## 1. Protected Class Reminder
List all protected classes under the Fair Housing Act and any state-specific additions for ${states.join(", ") || "Massachusetts"} (including source of income, sexual orientation, gender identity where applicable).

## 2. Prohibited Practices Checklist
Provide a bullet-point checklist of practices that are PROHIBITED. Include:
- Steering, redlining, discriminatory advertising language
- Refusing to show properties, differential terms
- Familial status and disability accommodation requirements

## 3. AI-Assisted Analysis Compliance
When using AI tools for real estate analysis:
- Do NOT input client demographic data or ask AI to infer demographics
- Review AI outputs for any language that describes neighborhood demographics in ways that could constitute steering
- Ensure analysis focuses on objective property and market factors only

## 4. Required Disclosures
List required fair housing disclosures and where they must appear (listings, websites, offices).

## 5. This Month's Self-Audit Questions
Provide 5 specific yes/no questions the broker should ask themselves about the past month's activities.

## 6. Resources
List the HUD Fair Housing complaint hotline, relevant state agency contacts, and training resources.

---
IMPORTANT: This review is generated by AI and is for educational/training purposes only. It does not constitute legal advice. Consult a licensed attorney for specific compliance questions.`;

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Auth: admin or scheduled (no user context for scheduled jobs)
    let isAuthorized = false;
    try {
      const user = await base44.auth.me();
      if (user?.role === "admin" || user?.role === "platform_owner") isAuthorized = true;
    } catch (_) {
      // Scheduled job — check for service-role context
      isAuthorized = true;
    }
    if (!isAuthorized) return Response.json({ error: "Forbidden" }, { status: 403 });

    const now = new Date();
    const period = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;

    // Get all orgs with compliance enabled
    const orgs = await base44.asServiceRole.entities.Organization.filter({
      fair_housing_compliance_enabled: true,
    });

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) return Response.json({ error: "ANTHROPIC_API_KEY not set" }, { status: 500 });

    const results = [];

    for (const org of orgs) {
      // Skip if review already exists for this period
      const existing = await base44.asServiceRole.entities.FairHousingReview.filter({
        org_id: org.id,
        review_period_month: period,
      });
      if (existing.length > 0) {
        results.push({ org: org.name, status: "already_exists" });
        continue;
      }

      // Find the highest-hierarchy reviewer
      const memberships = await base44.asServiceRole.entities.OrgMembership.filter({
        org_id: org.id,
        status: "active",
      });

      let reviewer = memberships.find((m) => m.role_in_org === "brokerage_admin") ||
                     memberships.find((m) => m.role_in_org === "team_lead");

      if (!reviewer) {
        results.push({ org: org.name, status: "no_reviewer" });
        continue;
      }

      // Generate review via Claude
      const prompt = REVIEW_PROMPT(org.name, org.licensed_markets || ["MA"], period);

      const anthropicRes = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "content-type": "application/json",
        },
        body: JSON.stringify({
          model: "claude-opus-4-5",
          max_tokens: 3000,
          messages: [{ role: "user", content: prompt }],
        }),
      });

      if (!anthropicRes.ok) {
        const err = await anthropicRes.text();
        console.error(`[fairHousing] Claude error for org ${org.name}:`, err);
        results.push({ org: org.name, status: "claude_error", error: err });
        continue;
      }

      const claudeData = await anthropicRes.json();
      const reviewText = claudeData.content?.[0]?.text || "";

      // Store review
      const review = await base44.asServiceRole.entities.FairHousingReview.create({
        org_id: org.id,
        reviewer_email: reviewer.user_email,
        review_period_month: period,
        licensed_states: org.licensed_markets || ["MA"],
        review_text: reviewText,
        review_generation_model: "claude-opus-4-5",
        status: "pending",
        liability_disclosure_accepted: false,
      });

      // Log privacy event
      await base44.asServiceRole.entities.PrivacyLog.create({
        event_type: "org_created", // reusing closest type — fair housing generated
        actor_email: "system",
        org_id: org.id,
        entity_type: "FairHousingReview",
        entity_id: review.id,
        metadata: { period, generated_for: reviewer.user_email },
      });

      results.push({ org: org.name, status: "generated", reviewId: review.id });
    }

    console.log("[generateFairHousingReviews] results:", JSON.stringify(results));
    return Response.json({ period, processed: results.length, results });

  } catch (error) {
    console.error("[generateFairHousingReviews] error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});