/**
 * crmPush — Push analysis key findings to a connected CRM.
 * Supports: Follow Up Boss, kvCORE, Salesforce, Lofty.
 * Pushes a formatted key-findings summary (NOT full output_text).
 * Logs every attempt to CrmPushLog.
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const ALLOWED_CRM_DOMAINS = [
  'followupboss.com',
  'api.followupboss.com',
  'kvcore.com',
  'api.kvcore.com',
  'salesforce.com',
  'login.salesforce.com',
  'lofty.com',
  'api.lofty.com',
];

function validateCrmUrl(url) {
  try {
    const parsed = new URL(url);
    const domain = parsed.hostname;
    if (!ALLOWED_CRM_DOMAINS.some(d => domain === d || domain.endsWith('.' + d))) {
      throw new Error(`CRM URL domain not allowed: ${domain}`);
    }
    if (parsed.protocol !== 'https:') {
      throw new Error('CRM URL must use HTTPS');
    }
    return parsed.toString();
  } catch (e) {
    if (e.message.startsWith('CRM URL')) throw e;
    throw new Error(`Invalid CRM URL: ${e.message}`);
  }
}

// Build a concise key-findings summary safe to push to CRM
function buildKeySummary(analysis) {
  const intake = analysis.intake_data || {};
  const lines = [
    `PropPrompt™ Analysis — ${analysis.assessment_type?.replace(/_/g, ' ').toUpperCase()}`,
    `Property: ${intake.address || 'N/A'}`,
    `Type: ${analysis.property_type?.replace(/_/g, ' ')} | Platform: ${analysis.ai_platform}`,
    `Date: ${new Date(analysis.completed_at || analysis.created_date).toLocaleDateString()}`,
    '',
    'Key findings are available in the full PropPrompt™ analysis report.',
    'Generated by PropPrompt™ — AI-calibrated real estate analysis by Sherwood & Company.',
    '',
    'DISCLAIMER: AI-generated analysis for professional reference only. Not a BPO or appraisal.',
  ];
  return lines.join('\n');
}

// --- Provider-specific push implementations ---

async function pushToFollowUpBoss(conn, analysis, summary) {
  const apiKey = conn.encrypted_api_key; // stored decrypted via resolveApiKey waterfall
  const url = validateCrmUrl('https://api.followupboss.com/v1/events');
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${btoa(apiKey + ':')}`,
      'Content-Type': 'application/json',
      'X-System': 'PropPrompt',
      'X-System-Key': apiKey,
    },
    body: JSON.stringify({
      source: 'PropPrompt™ Analysis',
      type: 'Note',
      message: summary,
      person: { emails: [{ value: analysis.run_by_email }] },
    }),
  });
  const body = await res.json().catch(() => ({}));
  return { ok: res.ok, status: res.status, body };
}

async function pushToKvcore(conn, analysis, summary) {
  const instanceUrl = conn.crm_account_name || 'https://api.kvcore.com';
  const token = conn.encrypted_api_key;
  const validatedUrl = validateCrmUrl(`${instanceUrl}/api/v1/notes`);
  const res = await fetch(validatedUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      note: summary,
      contact_email: analysis.run_by_email,
      source: 'PropPrompt',
    }),
  });
  const body = await res.json().catch(() => ({}));
  return { ok: res.ok, status: res.status, body };
}

async function pushToSalesforce(conn, analysis, summary) {
  // Use stored OAuth access token
  const accessToken = conn.oauth_access_token;
  const instanceUrl = conn.crm_account_name; // store Salesforce instance URL here
  const url = validateCrmUrl(instanceUrl);

  // Create Task record
  const validatedUrl = validateCrmUrl(`${instanceUrl}/services/data/v58.0/sobjects/Task`);
  const res = await fetch(validatedUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      Subject: `PropPrompt™ Analysis — ${analysis.assessment_type?.replace(/_/g, ' ')}`,
      Description: summary,
      Status: 'Completed',
      Priority: 'Normal',
      ActivityDate: new Date().toISOString().split('T')[0],
    }),
  });
  const body = await res.json().catch(() => ({}));
  return { ok: res.ok, status: res.status, body };
}

async function pushToLofty(conn, analysis, summary) {
  const apiKey = conn.encrypted_api_key;
  const contactId = conn.crm_user_id; // store CRM contact ID here
  const url = validateCrmUrl(`https://api.lofty.com/api/v1/contacts/${contactId}/notes`);
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ content: summary, type: 'note' }),
  });
  const body = await res.json().catch(() => ({}));
  return { ok: res.ok, status: res.status, body };
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { analysisId, connectionId } = await req.json();
    if (!analysisId || !connectionId) {
      return Response.json({ error: 'analysisId and connectionId required' }, { status: 400 });
    }

    // Load analysis — ownership check
    const records = await base44.asServiceRole.entities.Analysis.filter({ id: analysisId });
    const analysis = records[0];
    if (!analysis) return Response.json({ error: 'Analysis not found' }, { status: 404 });
    if (analysis.run_by_email !== user.email && user.role !== 'platform_owner') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    // Load CRM connection
    const conns = await base44.asServiceRole.entities.CrmConnection.filter({ id: connectionId });
    const conn = conns[0];
    if (!conn || conn.user_email !== user.email) {
      return Response.json({ error: 'CRM connection not found' }, { status: 404 });
    }

    const summary = buildKeySummary(analysis);
    const pushedAt = new Date().toISOString();

    // Create log entry (pending)
    const log = await base44.asServiceRole.entities.CrmPushLog.create({
      analysis_id: analysisId,
      crm_connection_id: connectionId,
      user_email: user.email,
      crm_provider: conn.crm_provider,
      push_type: conn.default_push_format || 'note',
      status: 'pending',
      pushed_at: pushedAt,
    });

    // Execute push
    let result = null;
    try {
      const provider = conn.crm_provider;
      if (provider === 'follow_up_boss') result = await pushToFollowUpBoss(conn, analysis, summary);
      else if (provider === 'kvcore') result = await pushToKvcore(conn, analysis, summary);
      else if (provider === 'salesforce') result = await pushToSalesforce(conn, analysis, summary);
      else if (provider === 'lofty') result = await pushToLofty(conn, analysis, summary);
      else throw new Error(`Unknown CRM provider: ${provider}`);
    } catch (pushErr) {
      console.error(`[crmPush] Push error for ${conn.crm_provider}:`, pushErr);
      await base44.asServiceRole.entities.CrmPushLog.update(log.id, {
        status: 'failed',
        error_message: pushErr.message,
        http_status_code: 0,
      });
      return Response.json({ error: pushErr.message, logId: log.id }, { status: 500 });
    }

    const success = result.ok;

    await base44.asServiceRole.entities.CrmPushLog.update(log.id, {
      status: success ? 'success' : 'failed',
      http_status_code: result.status,
      error_message: success ? null : JSON.stringify(result.body),
      crm_record_id: result.body?.id || null,
    });

    // Update analysis crm_push_status
    await base44.asServiceRole.entities.Analysis.update(analysisId, {
      crm_push_status: success ? 'pushed' : 'failed',
    });

    // Privacy log
    await base44.asServiceRole.entities.PrivacyLog.create({
      event_type: 'crm_connected',
      actor_email: user.email,
      entity_type: 'Analysis',
      entity_id: analysisId,
      org_id: analysis.org_id,
      metadata: { provider: conn.crm_provider, success, httpStatus: result.status },
    });

    console.log(`[crmPush] ${conn.crm_provider} push ${success ? 'SUCCESS' : 'FAILED'} for analysis=${analysisId}`);
    return Response.json({ success, status: result.status, logId: log.id });

  } catch (error) {
    console.error('[crmPush] error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});