import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { Copy, Download, Mail, CheckCircle, AlertCircle, Loader2, ChevronRight } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import jsPDF from "jspdf";

const SECTIONS = [
  "Initializing",
  "Assembling Prompt",
  "Connecting to Claude",
  "Generating Analysis",
  "Finalizing",
];

const DISCLAIMER = `**DISCLAIMER:** This analysis is generated by artificial intelligence and is intended solely as a professional research aid for licensed real estate practitioners. It does not constitute an appraisal, a Broker Price Opinion (BPO), or legal advice. All figures, valuations, and recommendations must be independently verified by the agent/broker of record before use in any client-facing communication. Sherwood & Company and its affiliates assume no liability for decisions made based on AI-generated content. © 2026 Sherwood & Company. PropPrompt™ is a proprietary system.`;

export default function AnalysisRun() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const urlParams = new URLSearchParams(window.location.search);
  const analysisId = urlParams.get("id");

  const [phase, setPhase] = useState(0); // 0-4 maps to SECTIONS
  const [output, setOutput] = useState("");
  const [done, setDone] = useState(false);
  const [error, setError] = useState(null);
  const [tokensUsed, setTokensUsed] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [copied, setCopied] = useState(false);
  const outputRef = useRef(null);
  const sseRef = useRef(null);

  useEffect(() => {
    if (!analysisId) {
      setError("No analysis ID provided.");
      return;
    }
    runAnalysis();
    return () => sseRef.current?.close();
  }, [analysisId]);

  // Auto-scroll as tokens arrive
  useEffect(() => {
    if (outputRef.current && !done) {
      outputRef.current.scrollTop = outputRef.current.scrollHeight;
    }
  }, [output]);

  async function runAnalysis() {
    try {
      // Load analysis metadata
      setPhase(0);
      const analyses = await base44.entities.Analysis.filter({ id: analysisId });
      const a = analyses[0];
      if (!a) { setError("Analysis not found."); return; }
      setAnalysis(a);

      // Step 1: Assemble prompt server-side
      setPhase(1);
      const assembleRes = await base44.functions.invoke("assemblePrompt", { analysisId });
      if (assembleRes.data?.error) throw new Error(assembleRes.data.error);

      // Step 2: Open SSE stream
      setPhase(2);
      // We use fetch with ReadableStream to consume SSE
      const authToken = await getAuthToken();
      setPhase(3);

      const response = await fetch(`${import.meta.env.VITE_API_BASE_URL || ""}/api/functions/claudeStream`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
        },
        body: JSON.stringify({ analysisId, model: "claude-sonnet-4-6" }),
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.error || "Stream failed");
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done: streamDone, value } = await reader.read();
        if (streamDone) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop();

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          const data = line.slice(6).trim();
          try {
            const event = JSON.parse(data);
            if (event.type === "token") {
              setOutput(prev => prev + event.text);
            } else if (event.type === "done") {
              setTokensUsed(event.tokensUsed);
              setPhase(4);
              setDone(true);
            } else if (event.type === "error") {
              throw new Error(event.message);
            }
          } catch (_) {}
        }
      }
    } catch (e) {
      setError(e.message);
    }
  }

  async function getAuthToken() {
    // base44 SDK exposes the token via the client config
    try {
      const client = base44;
      return client._token || client.token || null;
    } catch {
      return null;
    }
  }

  function handleCopy() {
    const text = output + "\n\n" + DISCLAIMER;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Copied to clipboard" });
  }

  function handleDownloadPDF() {
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const lines = doc.splitTextToSize(output.replace(/[#*`]/g, ""), 480);
    doc.setFontSize(10);
    doc.text(lines, 60, 60);
    // Disclaimer
    const discLines = doc.splitTextToSize(DISCLAIMER.replace(/\*\*/g, ""), 480);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(discLines, 60, doc.internal.pageSize.height - 80);
    const title = analysis
      ? `PropPrompt_${analysis.assessment_type}_${analysis.property_type}`
      : "PropPrompt_Analysis";
    doc.save(`${title}.pdf`);
    toast({ title: "PDF downloaded" });
  }

  function handleEmail() {
    const subject = analysis
      ? `PropPrompt™ Analysis — ${analysis.assessment_type?.replace(/_/g, " ")}`
      : "PropPrompt™ Analysis";
    const body = encodeURIComponent(output.slice(0, 2000) + "\n\n[Full analysis attached]");
    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${body}`);
  }

  return (
    <div className="min-h-screen bg-[#FAF8F4] flex flex-col">
      {/* Header */}
      <div className="bg-[#1A3226] text-white px-6 py-4 flex items-center justify-between">
        <div>
          <p className="text-[#B8982F] text-xs font-medium uppercase tracking-widest mb-0.5">PropPrompt™ v3.0</p>
          <h1 className="text-lg font-semibold">
            {analysis
              ? `${analysis.assessment_type?.replace(/_/g, " ")} · ${analysis.property_type?.replace(/_/g, " ")}`
              : "Analysis Run"}
          </h1>
        </div>
        {done && (
          <div className="flex items-center gap-2 text-xs text-white/60">
            <CheckCircle className="w-4 h-4 text-emerald-400" />
            Complete {tokensUsed ? `· ${tokensUsed.toLocaleString()} tokens` : ""}
          </div>
        )}
      </div>

      {/* Section Progress */}
      <div className="bg-white border-b border-[#1A3226]/10 px-6 py-3">
        <div className="flex items-center gap-1 overflow-x-auto">
          {SECTIONS.map((s, i) => (
            <div key={i} className="flex items-center gap-1 shrink-0">
              <div className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium transition-all
                ${i < phase ? "bg-emerald-100 text-emerald-700" :
                  i === phase ? "bg-[#1A3226] text-white" :
                  "bg-[#1A3226]/5 text-[#1A3226]/40"}`}>
                {i < phase ? <CheckCircle className="w-3 h-3" /> :
                 i === phase && !done ? <Loader2 className="w-3 h-3 animate-spin" /> :
                 i === phase && done ? <CheckCircle className="w-3 h-3" /> : null}
                {s}
              </div>
              {i < SECTIONS.length - 1 && (
                <ChevronRight className="w-3 h-3 text-[#1A3226]/20" />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col max-w-4xl mx-auto w-full px-4 lg:px-8 py-6 gap-6">
        {error ? (
          <div className="flex items-start gap-3 bg-red-50 border border-red-200 rounded-xl p-5 text-red-700">
            <AlertCircle className="w-5 h-5 mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold text-sm">Analysis Failed</p>
              <p className="text-sm mt-1 text-red-600">{error}</p>
            </div>
          </div>
        ) : (
          <>
            {/* Streaming Output */}
            <div
              ref={outputRef}
              className="bg-white rounded-2xl border border-[#1A3226]/10 p-6 lg:p-8 min-h-[400px] overflow-auto prose prose-sm max-w-none"
              style={{ maxHeight: "60vh" }}
            >
              {output ? (
                <ReactMarkdown>{output}</ReactMarkdown>
              ) : (
                <div className="flex items-center gap-3 text-[#1A3226]/40 py-16 justify-center">
                  <Loader2 className="w-6 h-6 animate-spin" />
                  <span className="text-sm">{SECTIONS[phase]}…</span>
                </div>
              )}
            </div>

            {/* Disclaimer — always rendered, visually distinct */}
            <div className="rounded-xl border border-[#B8982F]/20 bg-[#B8982F]/5 p-4 text-xs text-[#1A3226]/60 leading-relaxed">
              <p className="font-semibold text-[#B8982F] mb-1 uppercase tracking-wider text-[10px]">Disclaimer</p>
              <ReactMarkdown>{DISCLAIMER}</ReactMarkdown>
            </div>
          </>
        )}
      </div>

      {/* Sticky Action Bar */}
      {(done || output.length > 100) && (
        <div className="sticky bottom-0 bg-white border-t border-[#1A3226]/10 px-6 py-3 flex items-center gap-3 justify-end shadow-lg">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            className="gap-2 border-[#1A3226]/20 text-[#1A3226]"
          >
            {copied ? <CheckCircle className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy Text"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleEmail}
            className="gap-2 border-[#1A3226]/20 text-[#1A3226]"
          >
            <Mail className="w-4 h-4" />
            Email
          </Button>
          <Button
            size="sm"
            onClick={handleDownloadPDF}
            className="gap-2 bg-[#1A3226] hover:bg-[#1A3226]/90 text-white"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </Button>
        </div>
      )}
    </div>
  );
}